[2021-12-01T16:23:01.412119+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/" (from "http://51.38.233.189/TrackerCovid19/")" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" (from \"http://51.38.233.189/TrackerCovid19/\") at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-01T16:23:01.577891+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:07.322478+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-01T16:23:07.325141+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:07.482257+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2975c5"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/2975c5","method":"GET"} []
[2021-12-01T16:23:12.535175+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-01T16:23:12.544446+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:23:12.564863+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-01T16:23:12.743893+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-01T16:23:12.774141+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-01T16:23:13.045943+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-01T16:23:13.059917+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:13.273556+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6bff63"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/6bff63","method":"GET"} []
[2021-12-01T16:23:15.726912+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-01T16:23:15.727579+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:23:15.730176+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:23:16.822973+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:23:16.833542+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:16.989330+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e1c223"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/e1c223","method":"GET"} []
[2021-12-01T16:25:46.783208+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-01T16:25:46.784112+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:25:46.789930+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:25:47.883241+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:25:47.894431+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:25:48.037611+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"23297e"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/23297e","method":"GET"} []
[2021-12-01T16:25:58.201714+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/_wdt"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/_wdt\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/_wdt/\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-12-01T16:25:58.378644+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:25:58.379558+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:26:32.046824+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-01T16:26:32.047625+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:26:32.054767+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:26:33.106061+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:26:33.120100+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:26:33.315900+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e58b0b"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/e58b0b","method":"GET"} []
[2021-12-01T16:26:34.902615+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-01T16:26:34.904167+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:26:34.909444+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-01T16:26:35.237569+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-01T16:26:35.265316+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-01T16:26:35.529061+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-01T16:26:35.534329+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:26:35.658537+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2fda54"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/2fda54","method":"GET"} []
[2021-12-02T06:54:58.865364+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T06:54:58.887864+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T06:54:59.042655+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T06:54:59.322318+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T06:54:59.353896+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T06:54:59.633227+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T06:54:59.680245+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\JsonException: "Syntax error for "https://coronavirusapifr.herokuapp.com/data/live/france"." at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php line 94 {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\JsonException(code: 4): Syntax error for \"https://coronavirusapifr.herokuapp.com/data/live/france\". at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php:94)"} []
[2021-12-02T06:54:59.913324+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T06:54:59.916754+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T06:55:00.207917+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"98631e"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/98631e","method":"GET"} []
[2021-12-02T06:55:26.055691+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T06:55:26.056725+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T06:55:26.064632+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T06:55:26.122070+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T06:55:26.150667+00:00] http_client.INFO: Request: "GET https://coronavirusapi.fr.herokuapp.com/data/live/france" [] []
[2021-12-02T06:55:26.460212+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\TransportException: "SSL peer certificate or SSH remote key was not OK for "https://coronavirusapi.fr.herokuapp.com/data/live/france"." at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php line 151 {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0): SSL peer certificate or SSH remote key was not OK for \"https://coronavirusapi.fr.herokuapp.com/data/live/france\". at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php:151)\n[previous exception] [object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0): SSL peer certificate or SSH remote key was not OK for \"https://coronavirusapi.fr.herokuapp.com/data/live/france\". at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Chunk/ErrorChunk.php:65)\n[previous exception] [object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0): SSL peer certificate or SSH remote key was not OK for \"https://coronavirusapi.fr.herokuapp.com/data/live/france\". at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CurlResponse.php:323)"} []
[2021-12-02T06:55:26.554322+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T06:55:26.559908+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T06:55:26.874312+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0e15ca"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/0e15ca","method":"GET"} []
[2021-12-02T06:55:40.573729+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T06:55:40.578815+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T06:55:40.582514+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T06:55:40.641647+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T06:55:40.680204+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T06:55:40.925592+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T06:55:40.927780+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\JsonException: "Syntax error for "https://coronavirusapifr.herokuapp.com/data/live/france"." at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php line 94 {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\JsonException(code: 4): Syntax error for \"https://coronavirusapifr.herokuapp.com/data/live/france\". at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php:94)"} []
[2021-12-02T06:55:40.957418+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T06:55:40.963079+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T06:55:41.125599+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"35a395"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/35a395","method":"GET"} []
[2021-12-02T07:05:10.619741+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:05:10.620527+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:05:10.629948+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:05:11.633491+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:05:11.635362+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\JsonException: "Syntax error for "https://coronavirusapifr.herokuapp.com/data/live/departements"." at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php line 94 {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\JsonException(code: 4): Syntax error for \"https://coronavirusapifr.herokuapp.com/data/live/departements\". at /var/www/html/TrackerCovid19/vendor/symfony/http-client/Response/CommonResponseTrait.php:94)"} []
[2021-12-02T07:05:11.664969+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:05:11.666258+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:05:11.924610+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f22219"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/f22219","method":"GET"} []
[2021-12-02T07:10:56.575079+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:10:56.575800+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:10:56.578617+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:10:57.678265+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:10:57.704111+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:10:57.972597+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1050e0"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/1050e0","method":"GET"} []
[2021-12-02T07:10:59.985364+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:10:59.985999+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:10:59.992447+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:11:00.221712+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:11:00.252733+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:11:00.489750+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:11:00.501948+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:11:00.770966+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"456f35"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/456f35","method":"GET"} []
[2021-12-02T07:12:41.222982+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:12:41.223734+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:12:41.229919+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:12:41.718390+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:12:41.749159+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:12:42.001450+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:12:42.010936+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:12:42.207713+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a9d032"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/a9d032","method":"GET"} []
[2021-12-02T07:13:00.371680+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:13:00.372489+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:13:00.380779+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:13:00.431876+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:13:00.465090+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:13:00.541959+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:13:00.542498+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:13:00.548443+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:13:00.608338+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:13:00.634169+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:13:00.722508+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:13:00.732313+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:13:00.898211+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:13:00.906504+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:13:01.089995+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"603e5f"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/603e5f","method":"GET"} []
[2021-12-02T07:15:37.232179+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:15:37.232830+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:15:37.239353+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:15:37.396016+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:15:37.418336+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:15:37.668844+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:15:37.674569+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:15:38.165588+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"90fce0"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/90fce0","method":"GET"} []
[2021-12-02T07:25:15.829860+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:25:15.833548+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:25:15.853023+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:25:15.957099+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:25:15.989244+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:25:16.247788+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:25:16.263432+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:25:16.450213+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"45aed9"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/45aed9","method":"GET"} []
[2021-12-02T07:25:23.872407+00:00] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_route":"_profiler","_controller":"web_profiler.controller.profiler::panelAction","token":"45aed9"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_profiler/45aed9?panel=logger","method":"GET"} []
[2021-12-02T07:37:10.247462+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:37:10.248191+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:37:10.255005+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:37:10.410216+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:37:10.440242+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:37:10.705870+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:37:10.714985+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:37:10.918536+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a83ebe"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/a83ebe","method":"GET"} []
[2021-12-02T07:45:15.902788+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:45:15.907076+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:45:15.926556+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:45:16.155171+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:45:16.186548+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:45:16.503052+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:45:16.572473+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Asset manifest file "/var/www/html/TrackerCovid19/public/build/manifest.json" does not exist.")." at /var/www/html/TrackerCovid19/templates/base.html.twig line 13 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Asset manifest file \"/var/www/html/TrackerCovid19/public/build/manifest.json\" does not exist.\"). at /var/www/html/TrackerCovid19/templates/base.html.twig:13)\n[previous exception] [object] (RuntimeException(code: 0): Asset manifest file \"/var/www/html/TrackerCovid19/public/build/manifest.json\" does not exist. at /var/www/html/TrackerCovid19/vendor/symfony/asset/VersionStrategy/JsonManifestVersionStrategy.php:75)"} []
[2021-12-02T07:45:16.697985+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:45:16.703539+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:45:17.026384+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"51c4de"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/51c4de","method":"GET"} []
[2021-12-02T07:45:34.300867+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:45:34.301657+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:45:34.308521+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:45:34.376170+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:45:34.401212+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:45:34.664031+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:45:34.681211+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:45:34.853772+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9949d3"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/9949d3","method":"GET"} []
[2021-12-02T07:52:16.587220+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:52:16.588405+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:52:16.599878+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:52:16.832532+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:52:16.855068+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:52:17.218865+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:52:17.230160+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:52:17.359675+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d29b0e"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/d29b0e","method":"GET"} []
[2021-12-02T07:52:18.438626+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:52:18.443353+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:52:18.445839+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:52:19.571906+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:52:19.578475+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:52:19.693061+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"778680"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/778680","method":"GET"} []
[2021-12-02T07:52:20.480807+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:52:20.481390+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:52:20.487992+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:52:20.551210+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:52:20.587804+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:52:20.818210+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:52:20.824591+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:52:20.959975+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b1b065"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/b1b065","method":"GET"} []
[2021-12-02T07:54:36.936111+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/home/Savoie"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/home/Savoie\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/home/Savoie/\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-12-02T07:54:37.008430+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:54:37.009438+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:54:37.143512+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cb34e7"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/cb34e7","method":"GET"} []
[2021-12-02T07:54:39.919228+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T07:54:39.919980+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:54:39.922585+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:54:40.160420+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T07:54:40.186119+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:54:40.457809+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T07:54:40.468881+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:54:40.611849+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f23443"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/f23443","method":"GET"} []
[2021-12-02T07:54:41.454242+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:54:41.458676+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:54:41.460562+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:54:42.436115+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:54:42.441408+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:54:42.575761+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4fba8f"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/4fba8f","method":"GET"} []
[2021-12-02T07:56:51.261274+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:56:51.261956+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:56:51.268547+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:56:52.380293+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:56:52.395254+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:56:52.518186+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cf8a24"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/cf8a24","method":"GET"} []
[2021-12-02T07:56:53.806081+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:56:53.806664+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:56:53.812718+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:56:54.825921+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T07:56:54.836746+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:56:55.040992+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2519c6"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/2519c6","method":"GET"} []
[2021-12-02T07:58:00.875614+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:58:00.876437+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:58:00.883311+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/rhone" [] []
[2021-12-02T07:58:01.888288+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/rhone" [] []
[2021-12-02T07:58:01.893514+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:58:02.053667+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1e8722"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/1e8722","method":"GET"} []
[2021-12-02T07:58:31.915989+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T07:58:31.916935+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T07:58:31.923351+00:00] php.CRITICAL: Uncaught Error: Too few arguments to function App\Service\CallApiService::getDepData(), 0 passed in /var/www/html/TrackerCovid19/src/Controller/DepartementController.php on line 19 and exactly 1 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Service\\CallApiService::getDepData(), 0 passed in /var/www/html/TrackerCovid19/src/Controller/DepartementController.php on line 19 and exactly 1 expected at /var/www/html/TrackerCovid19/src/Service/CallApiService.php:31)"} []
[2021-12-02T07:58:31.928014+00:00] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Service\CallApiService::getDepData(), 0 passed in /var/www/html/TrackerCovid19/src/Controller/DepartementController.php on line 19 and exactly 1 expected" at /var/www/html/TrackerCovid19/src/Service/CallApiService.php line 31 {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Service\\CallApiService::getDepData(), 0 passed in /var/www/html/TrackerCovid19/src/Controller/DepartementController.php on line 19 and exactly 1 expected at /var/www/html/TrackerCovid19/src/Service/CallApiService.php:31)"} []
[2021-12-02T07:58:31.959581+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:58:31.960680+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:58:32.086668+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f919e8"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/f919e8","method":"GET"} []
[2021-12-02T07:58:36.523010+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/rhone"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/rhone\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/departement/rhone/\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-12-02T07:58:36.592056+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:58:36.593135+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:58:36.781471+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"169b81"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/169b81","method":"GET"} []
[2021-12-02T07:59:26.375667+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/rhone"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/rhone\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/departement/rhone/\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-12-02T07:59:26.447852+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:59:26.448840+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:59:26.656618+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"019558"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/019558","method":"GET"} []
[2021-12-02T07:59:34.381569+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/departement/savoie/\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-12-02T07:59:34.453223+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:59:34.454432+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T07:59:34.675930+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0bceca"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/0bceca","method":"GET"} []
[2021-12-02T08:00:13.246290+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:00:13.248852+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:00:13.251419+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:00:14.339544+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:00:14.344444+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("department") to generate a URL for route "departement".")." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Some mandatory parameters are missing (\"department\") to generate a URL for route \"departement\".\"). at /var/www/html/TrackerCovid19/templates/base.html.twig:28)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException(code: 0): Some mandatory parameters are missing (\"department\") to generate a URL for route \"departement\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Generator/UrlGenerator.php:178)"} []
[2021-12-02T08:00:14.456194+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:00:14.457499+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:00:14.686680+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"069c46"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/069c46","method":"GET"} []
[2021-12-02T08:01:56.765534+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:01:56.767049+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:01:56.777898+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:01:57.691182+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:01:57.699255+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "department" does not exist." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"department\" does not exist. at /var/www/html/TrackerCovid19/templates/base.html.twig:28)"} []
[2021-12-02T08:01:57.725678+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:01:57.726640+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:01:57.891025+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a18b58"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/a18b58","method":"GET"} []
[2021-12-02T08:02:23.226759+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:02:23.227542+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:02:23.235123+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:02:24.288814+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:02:24.299693+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "department" does not exist." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"department\" does not exist. at /var/www/html/TrackerCovid19/templates/base.html.twig:28)"} []
[2021-12-02T08:02:24.327191+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:02:24.328449+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:02:24.532841+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cce973"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/cce973","method":"GET"} []
[2021-12-02T08:02:36.199584+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:02:36.203287+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:02:36.206499+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:02:37.220766+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:02:37.235490+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "departement" does not exist." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"departement\" does not exist. at /var/www/html/TrackerCovid19/templates/base.html.twig:28)"} []
[2021-12-02T08:02:37.264900+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:02:37.266009+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:02:37.494424+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9c9d5b"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/9c9d5b","method":"GET"} []
[2021-12-02T08:03:07.397105+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:03:07.398932+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:03:07.402335+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:03:08.515687+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:03:08.526299+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Key "lib_dep" for array with keys "0" does not exist." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"lib_dep\" for array with keys \"0\" does not exist. at /var/www/html/TrackerCovid19/templates/base.html.twig:28)"} []
[2021-12-02T08:03:08.581781+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:03:08.586997+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:03:08.900605+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e7927d"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/e7927d","method":"GET"} []
[2021-12-02T08:03:24.830266+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:03:24.835039+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:03:24.838367+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:03:25.864914+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:03:25.870310+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("department") to generate a URL for route "departement".")." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Some mandatory parameters are missing (\"department\") to generate a URL for route \"departement\".\"). at /var/www/html/TrackerCovid19/templates/base.html.twig:28)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException(code: 0): Some mandatory parameters are missing (\"department\") to generate a URL for route \"departement\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Generator/UrlGenerator.php:178)"} []
[2021-12-02T08:03:25.967911+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:03:25.969053+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:03:26.306555+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"66ee08"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/66ee08","method":"GET"} []
[2021-12-02T08:04:40.798996+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:04:40.799817+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:04:40.807405+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:04:41.969459+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:04:41.980579+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("department") to generate a URL for route "departement".")." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Some mandatory parameters are missing (\"department\") to generate a URL for route \"departement\".\"). at /var/www/html/TrackerCovid19/templates/base.html.twig:28)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException(code: 0): Some mandatory parameters are missing (\"department\") to generate a URL for route \"departement\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Generator/UrlGenerator.php:178)"} []
[2021-12-02T08:04:42.078169+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:04:42.083505+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:04:42.426949+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d4af68"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/d4af68","method":"GET"} []
[2021-12-02T08:05:21.452176+00:00] request.INFO: Matched route "app_departement". {"route":"app_departement","route_parameters":{"_route":"app_departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:05:21.453093+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:05:21.455319+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:05:22.505445+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:05:22.517031+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("department") to generate a URL for route "app_departement".")." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Some mandatory parameters are missing (\"department\") to generate a URL for route \"app_departement\".\"). at /var/www/html/TrackerCovid19/templates/base.html.twig:28)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException(code: 0): Some mandatory parameters are missing (\"department\") to generate a URL for route \"app_departement\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Generator/UrlGenerator.php:178)"} []
[2021-12-02T08:05:22.620849+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:05:22.622111+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:05:22.946218+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9a20e3"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/9a20e3","method":"GET"} []
[2021-12-02T08:12:53.709072+00:00] request.INFO: Matched route "app_departement". {"route":"app_departement","route_parameters":{"_route":"app_departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:12:53.710029+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:12:53.722780+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:12:54.824883+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:12:54.842233+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("department") to generate a URL for route "app_departement".")." at /var/www/html/TrackerCovid19/templates/base.html.twig line 28 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Some mandatory parameters are missing (\"department\") to generate a URL for route \"app_departement\".\"). at /var/www/html/TrackerCovid19/templates/base.html.twig:28)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException(code: 0): Some mandatory parameters are missing (\"department\") to generate a URL for route \"app_departement\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Generator/UrlGenerator.php:178)"} []
[2021-12-02T08:12:54.943562+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:12:54.944866+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:12:55.252128+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b16671"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/b16671","method":"GET"} []
[2021-12-02T08:13:24.462293+00:00] request.INFO: Matched route "app_departement". {"route":"app_departement","route_parameters":{"_route":"app_departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:13:24.463983+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:13:24.474943+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:13:25.544017+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:13:25.558105+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:13:25.774990+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1225d8"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/1225d8","method":"GET"} []
[2021-12-02T08:13:31.913597+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:13:31.914267+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:13:31.923038+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:13:31.999678+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:13:32.030496+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:13:32.321562+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:13:32.321837+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:13:33.342559+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:13:33.358450+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Notice: Undefined index: departements")." at /var/www/html/TrackerCovid19/templates/home/index.html.twig line 8 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Notice: Undefined index: departements\"). at /var/www/html/TrackerCovid19/templates/home/index.html.twig:8)\n[previous exception] [object] (ErrorException(code: 0): Notice: Undefined index: departements at /var/www/html/TrackerCovid19/var/cache/dev/twig/7e/7e207aefc53bb8c6b9ecde757c3982b43e165d8a8b1a4a0164834c25e4e9a24f.php:93)"} []
[2021-12-02T08:13:33.468359+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:13:33.472604+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:13:33.743742+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"860dde"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/860dde","method":"GET"} []
[2021-12-02T08:14:25.513157+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:14:25.513961+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:14:25.520583+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:14:25.671974+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:14:25.700164+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:14:25.984868+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:14:25.985119+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:14:26.831774+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:14:26.845825+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:14:27.039439+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4b12a0"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/4b12a0","method":"GET"} []
[2021-12-02T08:14:51.165284+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:14:51.166021+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:14:51.173230+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:14:51.309979+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:14:51.339786+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:14:51.656991+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:14:51.657272+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:14:52.581720+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:14:52.593070+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:14:52.829535+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"261d64"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/261d64","method":"GET"} []
[2021-12-02T08:14:54.976341+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:14:54.977005+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:14:54.984491+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:14:55.058715+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:14:55.086261+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:14:55.349905+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:14:55.350165+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:14:56.253536+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:14:56.264743+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:14:56.540462+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"dab28f"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/dab28f","method":"GET"} []
[2021-12-02T08:15:02.385814+00:00] request.INFO: Matched route "app_departement". {"route":"app_departement","route_parameters":{"_route":"app_departement","_controller":"App\\Controller\\DepartementController::index","department":"savoie"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie","method":"GET"} []
[2021-12-02T08:15:02.391047+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:15:02.399781+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:15:03.393265+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departement/savoie" [] []
[2021-12-02T08:15:03.397432+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:15:03.565880+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1e5729"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/1e5729","method":"GET"} []
[2021-12-02T08:15:53.328994+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/departement/savoie\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/departement/savoie/\". at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-12-02T08:15:53.394163+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:15:53.399256+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:15:53.620385+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b283ee"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/b283ee","method":"GET"} []
[2021-12-02T08:15:58.768703+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T08:15:58.770117+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:15:58.788587+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:15:59.814319+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:15:59.835666+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:16:00.074414+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"733d64"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/733d64","method":"GET"} []
[2021-12-02T08:16:02.375260+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:16:02.375972+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:16:02.383537+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:16:02.620100+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:16:02.652061+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:16:02.909865+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:16:02.928471+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:16:03.431700+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"98734c"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/98734c","method":"GET"} []
[2021-12-02T08:20:34.522481+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:20:34.523718+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:20:34.532461+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:20:35.473075+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:20:35.503000+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:20:35.788054+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:20:35.799449+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:20:36.127683+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d28c0c"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/d28c0c","method":"GET"} []
[2021-12-02T08:27:18.657986+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T08:27:18.663288+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:27:18.671061+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:27:19.712741+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T08:27:19.723328+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:27:19.885443+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"35a934"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/35a934","method":"GET"} []
[2021-12-02T08:27:20.664546+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:27:20.665084+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:27:20.675602+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:27:20.830072+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:27:20.860425+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:27:21.135847+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:27:21.144574+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:27:21.329092+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"15f0fb"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/15f0fb","method":"GET"} []
[2021-12-02T08:46:41.358243+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T08:46:41.360585+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T08:46:41.380025+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:46:42.121897+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T08:46:42.151038+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:46:42.438118+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T08:46:42.448620+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:46:42.609706+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"443357"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/443357","method":"GET"} []
[2021-12-02T08:53:50.634435+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:53:50.643333+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:01.679656+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:01.708581+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:02.645767+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:02.658985+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:03.464991+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:03.476785+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:03.718046+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:03.726919+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:04.002413+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:04.008734+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:04.232751+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:04.250916+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:04.482477+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:04.496612+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:04.677790+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:04.692974+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T08:58:40.382419+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T08:58:40.395328+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:00:22.167191+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T09:00:22.170091+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:00:35.132335+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:00:35.133953+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:00:35.156962+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:00:35.735023+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:00:35.768416+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:00:36.060067+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:00:36.071210+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:00:36.226510+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5fc9a5"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/5fc9a5","method":"GET"} []
[2021-12-02T09:09:26.956612+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:26.962944+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:26.992683+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:28.165846+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:28.166368+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:28.179614+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:28.313317+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:28.313806+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:28.322449+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:28.576182+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:28.576843+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:28.582732+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:28.701489+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:28.702029+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:28.708766+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:28.833858+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:28.834442+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:28.841982+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:29.067499+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:29.068335+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:29.082951+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:09:29.244066+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:09:29.244606+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:09:29.255664+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:10:42.372531+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:10:42.373468+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:10:42.381057+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:10:42.542989+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:10:42.572356+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:10:42.852960+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:10:42.872059+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:10:43.080295+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6ea86c"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/6ea86c","method":"GET"} []
[2021-12-02T09:10:58.553587+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:10:58.554403+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:10:58.562136+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:10:58.710560+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:10:58.743824+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:10:59.007537+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:10:59.022102+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:10:59.262159+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e03c7b"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/e03c7b","method":"GET"} []
[2021-12-02T09:13:47.737667+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T09:13:47.738393+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:13:47.745856+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T09:13:49.084982+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T09:13:49.111829+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:13:49.339868+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a89f94"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/a89f94","method":"GET"} []
[2021-12-02T09:13:50.268414+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:13:50.269071+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:13:50.272806+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:13:50.472384+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:13:50.500618+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:13:50.750754+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:13:50.756359+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:13:50.966866+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d9653c"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/d9653c","method":"GET"} []
[2021-12-02T09:15:57.640595+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:15:57.641439+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:15:57.664093+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:15:57.747608+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"7cc88f"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/7cc88f","method":"GET"} []
[2021-12-02T09:16:14.348575+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:16:14.349350+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:16:14.356126+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:16:14.524658+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:16:14.543871+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:16:14.819033+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:16:14.838407+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:16:14.960373+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f83788"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/f83788","method":"GET"} []
[2021-12-02T09:22:33.322173+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:22:33.327230+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:22:33.330485+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:22:34.317200+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:22:34.348185+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:22:34.609261+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:22:34.623920+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:22:34.920015+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f424fe"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/f424fe","method":"GET"} []
[2021-12-02T09:22:39.731073+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/" (from "http://51.38.233.189/TrackerCovid19/")" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" (from \"http://51.38.233.189/TrackerCovid19/\") at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T09:22:39.733564+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:49:43.932067+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/" (from "http://51.38.233.189/TrackerCovid19/")" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" (from \"http://51.38.233.189/TrackerCovid19/\") at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-02T09:49:43.938459+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:49:46.358217+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:49:46.362475+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:49:46.365641+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:49:47.002230+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:49:47.030475+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:49:47.335243+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:49:47.344842+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:49:47.522912+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5c645f"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/5c645f","method":"GET"} []
[2021-12-02T09:49:51.304638+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-02T09:49:51.305343+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:49:51.312103+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T09:49:52.481484+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-02T09:49:52.503828+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:49:52.755447+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"46f095"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/46f095","method":"GET"} []
[2021-12-02T09:49:58.716178+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-02T09:49:58.716936+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-02T09:49:58.724488+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:49:58.817215+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-02T09:49:58.847530+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:49:59.132955+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-02T09:49:59.138621+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-02T09:49:59.339598+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cb32fe"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/cb32fe","method":"GET"} []
