[2021-12-01T16:23:01.412119+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/" (from "http://51.38.233.189/TrackerCovid19/")" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/\" (from \"http://51.38.233.189/TrackerCovid19/\") at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-01T16:23:01.577891+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:07.322478+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://51.38.233.189/TrackerCovid19/public/index.php/"" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://51.38.233.189/TrackerCovid19/public/index.php/\" at /var/www/html/TrackerCovid19/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/html/TrackerCovid19/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-12-01T16:23:07.325141+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:07.482257+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2975c5"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/2975c5","method":"GET"} []
[2021-12-01T16:23:12.535175+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/home","method":"GET"} []
[2021-12-01T16:23:12.544446+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:23:12.564863+00:00] http_client.INFO: Request: "GET https://api.covid19api.com/total/country/france" [] []
[2021-12-01T16:23:12.743893+00:00] http_client.INFO: Response: "200 https://api.covid19api.com/total/country/france" [] []
[2021-12-01T16:23:12.774141+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-01T16:23:13.045943+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/france" [] []
[2021-12-01T16:23:13.059917+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:13.273556+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6bff63"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/6bff63","method":"GET"} []
[2021-12-01T16:23:15.726912+00:00] request.INFO: Matched route "departement". {"route":"departement","route_parameters":{"_route":"departement","_controller":"App\\Controller\\DepartementController::index"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/departement","method":"GET"} []
[2021-12-01T16:23:15.727579+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-01T16:23:15.730176+00:00] http_client.INFO: Request: "GET https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:23:16.822973+00:00] http_client.INFO: Response: "200 https://coronavirusapifr.herokuapp.com/data/live/departements" [] []
[2021-12-01T16:23:16.833542+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/html/TrackerCovid19/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-01T16:23:16.989330+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e1c223"},"request_uri":"http://51.38.233.189/TrackerCovid19/public/index.php/_wdt/e1c223","method":"GET"} []
